config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'customers#index'

  resources :customers do
    collection do
      get :replacements
    end
  end

  resources :customers, only: [:edit, :update, :index, :show]
  resources :replacements, only: [:index, :show, :new, :edit, :update, :destroy]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :replacements
  has_many :users

  validates :client_name, presence: true
  validates :teeptrak_id, presence: false

end

app/models/replacement.rb
class Replacement < ApplicationRecord
  belongs_to :customer

  validates :description, presence: true
  validates :return_content, presence: true
  validates :tablet_number, presence: true
  validates :customer_id, presence: true
  validates :internal_message, presence: true
  validates :received_date, presence: true
  validates :received_tracking, presence: true
  validates :tested, presence: true
  validates :replacement_number, presence: true
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :email])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :email])
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  layout "exchange"

  def create
    @customer = Customer.new(customer_params)
    if @customer.save
      redirect_to customer_path(@customer)
    else
      render 'new'
    end
  end

  def new
    @customer = Customer.new()
    # @customer.save
  end

  def index
    @customers = Customer.all
  end

  def destroy
    @customer = Customer.find(params[:id])
    # raise
    @customer.destroy
    redirect_to customer_path
  end


  def show
    @customer = Customer.find(params[:id])
    # authorize @customer
    # @replacement = Replacement.new
  end

  def update
    #raise
    @customer = Customer.find(params[:id])
    @customer.client_name = params[:customer][:client_name]
    @customer.teeptrak_id = params[:customer][:teeptrak_id]
    @customer.save
    redirect_to customer_path(@customer)
  end

  # def edit
  #   @customer = Customer.find(params[:id])
  # end

  private

  def customer_params
    params.require(:customer).permit(:client_name, :teeptrak_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :authenticate_user!, only: :home
  layout "exchange"

  def home
    #UserMailer.with(user: @user).welcome_email.deliver_later
    # raise
  end
end

app/controllers/replacements_controller.rb
class ReplacementsController < ApplicationController
  layout "exchange"
  def index
    @replacements = Replacement.all
    # UserMailer.with(user: @user).welcome_email.deliver_later
    # raise
  end

  def show
    @replacement = Replacement.find(params[:id])
  end

  def new
    @replacement = Replacement.new()
  end

  def create
    @replacement = Replacement.new(replacement_params)
    if @replacement.save
      redirect_to replacement_path(@replacement)
    else
      render 'new'
    end
  end

  def update
    #raise
    @replacement = Replacement.find(params[:id])
    @replacement.contact_first_name = params[:replacement][:contact_first_name]
    @replacement.contact_last_name = params[:replacement][:contact_last_name]
    @replacement.save
    redirect_to replacement_path(@replacement)
  end

  private

  def replacement_params
    params.require(:replacement).permit(:description, :tablet_number, :internal_message, :tested, :contact_first_name, :contact_last_name, :contact_email, :contact_phone)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/customers/edit.html.erb
<%# <%= simple_form_for(@customer) do |f| %>
  <%# <%= f.input :client_name %>
  <%# <%= f.submit %>
<%# <% end %>

app/views/customers/index.html.erb
<table class="table">
  <thead class="thead-light">
    <tr>
      <th scope="col">Return id</th>
      <th scope="col">Name</th>
      <th scope="col">TEEPTRAK id</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @customers.each do |customer| %>
    <% # raise %>
      <tr>
        <th scope="row"><%= customer.id %></th>
        <td><%=customer.client_name %></td>
        <td><%=customer.teeptrak_id %></td>
        <td>
          <%= link_to customer, { :method => :delete, :class => 'btn btn-sm btn-icon btn-bg-light btn-active-color-danger', data: {confirm: 'Are you sure you want to remove this customer?'}} do %>
            <span class="svg-icon svg-icon-2">
              <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
                <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                  <rect x="0" y="0" width="24" height="24"></rect>
                  <path d="M6,8 L6,20.5 C6,21.3284271 6.67157288,22 7.5,22 L16.5,22 C17.3284271,22 18,21.3284271 18,20.5 L18,8 L6,8 Z" fill="#000000" fill-rule="nonzero"></path>
                  <path d="M14,4.5 L14,4 C14,3.44771525 13.5522847,3 13,3 L11,3 C10.4477153,3 10,3.44771525 10,4 L10,4.5 L5.5,4.5 C5.22385763,4.5 5,4.72385763 5,5 L5,5.5 C5,5.77614237 5.22385763,6 5.5,6 L18.5,6 C18.7761424,6 19,5.77614237 19,5.5 L19,5 C19,4.72385763 18.7761424,4.5 18.5,4.5 L14,4.5 Z" fill="#000000" opacity="0.3"></path>
                </g>
              </svg>
            </span>
          <% end %>
          <%= link_to customer, { method: :get, :class => 'bi bi-pen' } do %>
            <span class="bi bi-pen">
              <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
                <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                  <rect x="0" y="0" width="24" height="24"></rect>
                  <path d="m13.498.795.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001zm-.644.766a.5.5 0 0 0-.707 0L1.95 11.756l-.764 3.057 3.057-.764L14.44 3.854a.5.5 0 0 0 0-.708l-1.585-1.585z" fill="#000000" opacity="0.3"></path>
                </g>
              </svg>
            </span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/customers/new.html.erb
<%= simple_form_for(@customer) do |f| %>
  <%= f.input :client_name %>
  <%= f.submit %>
<% end %>

app/views/customers/show.html.erb
<%= simple_form_for(@customer) do |f| %>
  <%= f.input :client_name, as: :string %>
  <%= f.input :teeptrak_id, as: :string %>
  <%= f.button :submit, 'Modifier mes informations', class: "btn btn-info rounded-lg mb-5" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TeeptrakExchange</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    
    <%= favicon_link_tag asset_path('favicon.png') %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/exchange.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TEEPTRAK Exchange</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    
    <%= render 'shared/navbar' %>
    
    <%= favicon_link_tag asset_path('favicon.png') %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<% if signed_in? %>

  <table class="front" summary="For signed-in users">
    <tr>
      <td class="main">
        <h1 class="micropost">Mes tickets</h1>
      </td>
      <td class="sidebar round">
      </td>
    </tr>
  </table>

<% else %>

<h1>Sample App</h1>
<p>
  This is the home page for the <a href=""></a> sample application.
</p>

<%= link_to "Sign up now!", signup_path, :class => "signup_button round" %>
<% end %>

app/views/replacements/index.html.erb
<table class="table">
  <thead class="thead-light">
    <tr>
      <th scope="col">Return id</th>
      <th scope="col">First name</th>
      <th scope="col">Last name</th>
      <th scope="col">Contact client</th>
      <th scope="col">Email</th>
      <th scope="col">Phone</th>
      <th scope="col">Description</th>
      <th scope="col">To bill</th>
      <th scope="col">Return content</th>
      <th scope="col">Tablet number</th>
      <th scope="col">Received date</th>
      <th scope="col">Internal message</th>
      <th scope="col">Received tracking</th>
      <th scope="col">Tested ?</th>
      <th scope="col">Owner id</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @replacements.each do |replacement| %>
    <% # raise %>
      <tr>
        <th scope="row"><%= replacement.id %></th>
        <td><%=replacement.customer_id %></td>
        <td><%=replacement.contact_last_name %></td>
        <td><%=replacement.contact_client %></td>
        <td><%=replacement.contact_email %></td>
        <td><%=replacement.contact_phone %></td>
        <td><%=replacement.description %></td>
        <td><%=replacement.to_bill %></td>
        <td><%=replacement.return_content %></td>
        <td><%=replacement.tablet_number %></td>
        <td><%=replacement.internal_message %></td>
        <td><%=replacement.received_date %></td>
        <td><%=replacement.received_tracking %></td>
        <td><%=replacement.tested %></td>
        <td><%=replacement.replacement_number %></td>
        <td><%=replacement.owner_id %></td>
        <td>
          <%= link_to replacement, { :method => :delete, :class => 'btn btn-sm btn-icon btn-bg-light btn-active-color-danger', data: {confirm: 'Are you sure you want to remove this replacement?'}} do %>
            <span class="svg-icon svg-icon-2">
              <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
                <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                  <rect x="0" y="0" width="24" height="24"></rect>
                  <path d="M6,8 L6,20.5 C6,21.3284271 6.67157288,22 7.5,22 L16.5,22 C17.3284271,22 18,21.3284271 18,20.5 L18,8 L6,8 Z" fill="#000000" fill-rule="nonzero"></path>
                  <path d="M14,4.5 L14,4 C14,3.44771525 13.5522847,3 13,3 L11,3 C10.4477153,3 10,3.44771525 10,4 L10,4.5 L5.5,4.5 C5.22385763,4.5 5,4.72385763 5,5 L5,5.5 C5,5.77614237 5.22385763,6 5.5,6 L18.5,6 C18.7761424,6 19,5.77614237 19,5.5 L19,5 C19,4.72385763 18.7761424,4.5 18.5,4.5 L14,4.5 Z" fill="#000000" opacity="0.3"></path>
                </g>
              </svg>
            </span>
          <% end %>
          <%= link_to replacement, { method: :get, :class => 'bi bi-pen' } do %>
            <span class="bi bi-pen">
              <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
                <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                  <rect x="0" y="0" width="24" height="24"></rect>
                  <path d="m13.498.795.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001zm-.644.766a.5.5 0 0 0-.707 0L1.95 11.756l-.764 3.057 3.057-.764L14.44 3.854a.5.5 0 0 0 0-.708l-1.585-1.585z" fill="#000000" opacity="0.3"></path>
                </g>
              </svg>
            </span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/replacements/show.html.erb
<%= simple_form_for(@replacement) do |f| %>
  <%= f.input :contact_last_name, as: :string %>
  <%= f.input :contact_first_name, as: :string %>
  <%= f.input :contact_client, as: :string %>
  <%= f.input :contact_email, as: :string%>
  <%= f.input :description, as: :string %>
  <%= f.input :return_content, as: :string %>
  <%= f.input :tablet_number, as: :string %>
  <%= f.input :internal_message, as: :string %>
  <%= f.input :received_date, as: :string %>
  <%= f.input :received_tracking, as: :string %>
  <%= f.input :tested, as: :boolean %>
  <%= f.input :replacement_number, as: :string %>
  <%= f.input :to_bill, as: :boolean %>
  <%= f.input :owner_id, as: :string %>
  <%= f.input :contact_phone, as: :string %>
  <%= f.button :submit, 'Modifier', class: "btn btn-info rounded-lg mb-5" %>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= inline_svg_tag "teeptrak_logo.svg", class: 'logo-default' %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Add customer", new_customer_path, class: "dropdown-item" %>
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/user/index.html.erb
<h1>hello</h1>